### ISSUE TITLE
Add how to build info to README

### ISSUE THREAD

**Issue by filfreire** [rafaelcpalmeida/multibanco_ifthenpay#2]
@rafaelcpalmeida 👋  

Similarly to installation, I would suggest adding a "How to Build" section on README file, so any newcomer who wants to tinker with the gem itself knows exactly what they need to build it locally.

**Comment by rafaelcpalmeida** [comment]
Great suggestion! I'll try to do it this week 😬

**Comment by rafaelcpalmeida** [comment]
Fixed with https://github.com/rafaelcpalmeida/multibanco_ifthenpay/commit/c1d4e7df8bbadaaa7a3f03a52a498facd484b61b.

**Comment by filfreire** [comment]
@rafaelcpalmeida 🎉
